### ISSUE TITLE
[feature-request] Passing options to git clone

### ISSUE THREAD

**Issue by Juliaria08** [wezm/git-grab#14]
Git-grab internally runs `git clone`, so it'd be neat to allow some git config option to pass options, or maybe some parameter to pass options to git clone, (I'd like to use this to set `--recurse-submodules --recurse-submodules` to get all submodules too)

**Comment by wezm** [comment]
Yes I think being able to pass options through to the git invocation does make sense. I also had the need to pass recurse-submodules the other day. I will close this one in favour of #9 and aim to work on it in the next day or so.
