### ISSUE TITLE
No issue, just thanks

### ISSUE THREAD

**Issue by bdmorin** [wezm/git-grab#2]
I appreciate this tool so much. I had a horky fish function that tried to do what this tool does *PERFECTLY* I wish this was the default for cloning, it does exactly what I need.

Great job, and THANK YOU!

**Comment by wezm** [comment]
Thank you! Glad it's useful. The kudos truely belong to @jmhodges though, as they are the one that originally came up with the idea. I just came up with this alternate implementation.
